# Generated by Django 3.0.8 on 2020-07-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20200729_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes_count',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='poster',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
