# Generated by Django 3.0.8 on 2020-08-04 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20200803_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follower_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following_count',
        ),
    ]
